//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuegoSennas_SitoWeb.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TP_IngWebEntities : DbContext
    {
        public TP_IngWebEntities()
            : base("name=TP_IngWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS_JUEGOS> CATEGORIAS_JUEGOS { get; set; }
        public virtual DbSet<CATEGORIAS_USUARIOS> CATEGORIAS_USUARIOS { get; set; }
        public virtual DbSet<CONTENIDOS> CONTENIDOS { get; set; }
        public virtual DbSet<ESTADOS_CONTENIDO> ESTADOS_CONTENIDO { get; set; }
        public virtual DbSet<ESTADOS_USUARIOS> ESTADOS_USUARIOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOS_CONTENIDOS> TIPOS_CONTENIDOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
