//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuegoSennas_SitoWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
        public int IdCategoria { get; set; }
        public int IdEstado { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Intereses { get; set; }
    
        public virtual CATEGORIAS_USUARIOS CATEGORIAS_USUARIOS { get; set; }
        public virtual ESTADOS_USUARIOS ESTADOS_USUARIOS { get; set; }
    }
}
